-- Apply after supabase_setup.sql, before deploying the new frontend.
BEGIN;
CREATE TABLE IF NOT EXISTS public.guestbook_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board text NOT NULL,
    name text NOT NULL CHECK (char_length(btrim(name)) BETWEEN 1 AND 20),
    text text NOT NULL CHECK (char_length(btrim(text)) BETWEEN 1 AND 1000),
    created_at timestamptz NOT NULL DEFAULT now(),
    legacy_id text UNIQUE,
    legacy_date text CHECK (char_length(legacy_date) <= 100)
);
CREATE INDEX IF NOT EXISTS guestbook_board_created_idx
    ON public.guestbook_entries (board, created_at DESC, id DESC);
ALTER TABLE public.guestbook_entries ENABLE ROW LEVEL SECURITY;
-- Remove any older policy on this table; permissive policies are OR-combined.
DO $$ DECLARE p record; BEGIN
    FOR p IN SELECT policyname FROM pg_policies WHERE schemaname = 'public' AND tablename = 'guestbook_entries' LOOP
        EXECUTE format('DROP POLICY %I ON public.guestbook_entries', p.policyname);
    END LOOP;
END $$;
REVOKE ALL ON public.guestbook_entries FROM anon, authenticated;
GRANT SELECT ON public.guestbook_entries TO anon, authenticated;
GRANT DELETE ON public.guestbook_entries TO authenticated;
GRANT ALL ON public.guestbook_entries TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.guestbook_entries_id_seq TO service_role;
CREATE POLICY guestbook_public_read ON public.guestbook_entries FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY guestbook_admin_delete ON public.guestbook_entries FOR DELETE TO authenticated
    USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

CREATE OR REPLACE FUNCTION public.submit_guestbook_entry(p_board text, p_name text, p_text text)
RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path = '' AS $$
BEGIN
    -- Serialize the rate check and insert across Edge Function instances.
    PERFORM pg_advisory_xact_lock(hashtext('retro_guestbook:' || p_board));
    IF (SELECT count(*) FROM public.guestbook_entries
        WHERE board = p_board AND created_at > now() - interval '1 minute') >= 30 THEN
        RAISE EXCEPTION 'Board rate limit reached' USING ERRCODE = 'P0001';
    END IF;
    INSERT INTO public.guestbook_entries(board, name, text) VALUES (p_board, btrim(p_name), btrim(p_text));
END $$;
REVOKE ALL ON FUNCTION public.submit_guestbook_entry(text, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.submit_guestbook_entry(text, text, text) TO service_role;
COMMIT;
