const projects=[
{id:'bible',title:'Bible<br>Project',category:'FAITH · WORD · IMAGE',url:'https://wordlight-bible.kkangdo.chatgpt.site/',ko:['Bible Project','말씀 속에서 만나는 새로운 하루','성경 66권을 읽고, 마음에 닿는 구절을 아름다운 말씀카드로 간직하세요.','말씀과 함께하는 하루','꽃이 핀 여름 발코니와 펼쳐진 성경'],en:['Bible Project','A new day with His word','Read all 66 books of the Korean Bible and keep meaningful verses as beautiful scripture cards.','A moment with the Word','An open Bible on a flower-filled summer balcony'],jp:['Bible Project','聖書と出会う新しい一日','韓国語の聖書全66巻を読み、心に響く一節を美しい聖句カードに。','聖書と過ごすひととき','花の咲く夏のバルコニーと開いた聖書']},
{id:'health',title:'Health<br>Lab',category:'HEALTH · EVERYDAY',url:'./health-landing/index.html',ko:['건강관리','몸과 마음을 위한 작은 습관','더 활기찬 일상을 위한 건강 이야기와 생활 속 작은 습관을 만나보세요.','나를 돌보는 작은 습관','푸른 강과 나무가 펼쳐진 여름 산책길'],en:['Health Lab','Small habits, brighter days','Explore health stories and everyday habits for a more energetic life.','Everyday care for yourself','A leafy summer walking path beside a blue river'],jp:['健康管理','心と体のための小さな習慣','健やかな毎日のための健康情報と、暮らしの中の小さな習慣。','自分をいたわる毎日','青い川と木々に囲まれた夏の散歩道']},
{id:'cooking',title:'One Cut<br>Kitchen',category:'FOOD · SIMPLE JOY',url:'./1cutdish/index.html',ko:['한컷요리','한 컷씩, 맛있는 일상','요리 과정을 만화처럼 쉽고 재미있게. 오늘의 한 끼를 한컷요리와 함께 준비해보세요.','쉽고 즐거운 한 끼','여름 발코니 식탁 위의 채소와 달걀을 곁들인 국수'],en:['One Cut Kitchen','A delicious story, frame by frame','Discover recipes through illustrated steps and find inspiration for your next meal.','A little joy in every meal','A bowl of noodles and vegetables on a sunny balcony'],jp:['ひとコマ料理','ひとコマずつ、おいしい毎日','漫画のように楽しくわかりやすい料理の手順。今日の一食を一緒に作りましょう。','手軽で楽しい一食','夏のバルコニーに置かれた野菜と卵の麺料理']},
{id:'recipe',title:'Recipe<br>Stories',category:'RECIPE · TOGETHER',url:'./recipe-community/index.html',ko:['레시피 커뮤니티','맛있는 이야기를 나누는 곳','좋아하는 레시피를 발견하고, 나만의 요리 이야기를 함께 나누는 공간입니다.','함께 나누는 맛있는 이야기','햇빛이 비치는 창가의 싱싱한 채소와 허브'],en:['Recipe Community','Good food brings us together','Discover recipes and share your own cooking stories with a community of food lovers.','Recipes worth sharing','Fresh vegetables and herbs beside a sunny kitchen window'],jp:['レシピ広場','おいしい話を分かち合う場所','お気に入りのレシピを見つけて、自分だけの料理の物語を分かち合いましょう。','みんなで楽しむレシピ','日差しが注ぐ窓辺の新鮮な野菜とハーブ']},
{id:'retro',title:'Retro<br>1980',category:'CULTURE · MEMORIES',url:'./retro-1980/index.html',ko:['Retro 1980','그 시절 골목에서 다시 만나요','골목길 놀이부터 그 시절 음악까지. 오래된 추억을 다시 만나는 시간 여행입니다.','다시 펼쳐보는 우리의 추억','파란 자동차가 주차된 여름날의 옛 동네 골목'],en:['Retro 1980','Meet me in the old neighborhood','From neighborhood games to favorite songs, rediscover the moments you remember.','A little trip down memory lane','A vintage blue car on a sunny old neighborhood street'],jp:['Retro 1980','あの頃の路地で、また会おう','路地裏の遊びから懐かしい音楽まで。思い出と再会する時間旅行へ。','あの日の思い出を開く','青い旧車が停まる夏の懐かしい路地']},
{id:'medidiet',title:'Medi<br>Diet',category:'NUTRITION · BALANCE',url:'https://romio215-coder.github.io/medidiet/',ko:['MediDiet','매일의 식사를 조금 더 건강하게','시니어를 위한 식단 관리 도우미. 나에게 맞는 건강한 식생활을 만들어가세요.','균형을 생각하는 매일의 식사','연어와 채소가 담긴 식사와 시원한 레몬 물'],en:['MediDiet','A little balance in every meal','A nutrition companion for seniors, helping you build healthier everyday eating habits.','Everyday meals in balance','Salmon, vegetables, and cool lemon water on a summer terrace'],jp:['MediDiet','毎日の食事を、もっと健やかに','シニアのための食事サポート。自分に合った健やかな食生活を育てましょう。','バランスのよい毎日の食事','夏のテラスに置かれた鮭と野菜の食事とレモン水']}
];
const translations={ko:{skip:'프로젝트 바로가기',tagline:'좋은 아이디어가\n좋은 일상을 만듭니다.',home:'홈',projects:'프로젝트',about:'소개',headline:'좋은 아이디어가\n좋은 일상을\n만듭니다.',intro:'건강, 음식, 추억, 신앙.\n일상을 조금 더 풍요롭게 만드는\n후추의 작은 프로젝트들입니다.',browse:'프로젝트 보기',visit:'프로젝트 열기',shelf:'책장 속 다른 이야기',footer:'작은 아이디어로, 조금 더 좋은 일상.',studio:'후추 스튜디오 ↗',previous:'이전 프로젝트',next:'다음 프로젝트',select:'프로젝트 선택'},en:{skip:'Skip to projects',tagline:'Good ideas make\neveryday life better.',home:'Home',projects:'Projects',about:'About',headline:'Good ideas.\nA better\neveryday.',intro:'Health, food, memories, and faith.\nA collection of little projects\nto enrich everyday life.',browse:'Explore projects',visit:'Open project',shelf:'More stories on the shelf',footer:'Little ideas. A better everyday.',studio:'Huchu Studio ↗',previous:'Previous project',next:'Next project',select:'Select project'},jp:{skip:'プロジェクトへ',tagline:'よいアイデアが\nよい日常をつくる。',home:'ホーム',projects:'プロジェクト',about:'紹介',headline:'よいアイデアが\nよい日常を\nつくる。',intro:'健康、料理、思い出、信仰。\n日常を少し豊かにする\n小さなプロジェクト集です。',browse:'プロジェクトを見る',visit:'サイトを開く',shelf:'本棚のほかの物語',footer:'小さなアイデアで、もっとよい毎日。',studio:'Huchu Studio ↗',previous:'前のプロジェクト',next:'次のプロジェクト',select:'プロジェクトを選択'}};
let selected=0,language='ko';try{const saved=localStorage.getItem('preferredLanguage');if(translations[saved])language=saved;}catch{}
const $=id=>document.getElementById(id),number=i=>String(i+1).padStart(2,'0');
function render(){const t=translations[language],p=projects[selected],copy=p[language];document.documentElement.lang=language==='jp'?'ja':language;document.querySelectorAll('[data-i18n]').forEach(el=>{el.textContent=t[el.dataset.i18n];el.style.whiteSpace='pre-line';});document.querySelectorAll('[data-language]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.language===language)));$('book-number').textContent=number(selected);$('page-count').innerHTML=number(selected)+' <i>/</i> 06';$('book-title').innerHTML=p.title;$('book-subtitle').textContent=copy[1];$('book-description').textContent=copy[2];$('book-category').textContent=p.category;$('project-link').href=p.url;$('hero-image').src=`./assets/summer-${p.id}.webp`;$('hero-image').alt=copy[4];$('previous').setAttribute('aria-label',t.previous);$('next').setAttribute('aria-label',t.next);
$('book-index').replaceChildren(...projects.map((project,i)=>{const b=document.createElement('button');b.className='index-item';b.dataset.project=String(i);b.setAttribute('aria-pressed',String(i===selected));b.innerHTML=`<span>${number(i)}</span>`;b.append(project[language][0]);b.addEventListener('click',()=>select(i));return b;}));
$('shelf').replaceChildren(...projects.flatMap((project,i)=>{if(i===selected)return[];const b=document.createElement('button');b.className='mini-book';b.dataset.project=String(i);b.setAttribute('aria-label',`${project[language][0]} — ${t.select}`);b.innerHTML=`<span class="mini-copy"><span class="mini-number">${number(i)} <small> / PROJECT</small></span><span class="mini-title">${project[language][0]}</span><span class="mini-category">${project.category.split(' · ')[0]}</span><span class="mini-desc">${project[language][3]}</span><span class="mini-arrow" aria-hidden="true">↗</span></span><img src="./assets/summer-${project.id}-small.webp" alt="" width="360" height="540" loading="lazy">`;b.addEventListener('click',()=>{select(i);$('project-link').focus({preventScroll:true});$('featured').scrollIntoView({block:'center',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});return[b];}));}
function select(i){const focused=document.activeElement;const indexFocus=focused?.closest('#book-index')?Number(focused.dataset.project):null;selected=(i+projects.length)%projects.length;render();if(indexFocus!==null)$('book-index').querySelector(`[data-project="${indexFocus}"]`).focus({preventScroll:true});}
$('previous').addEventListener('click',()=>select(selected-1));$('next').addEventListener('click',()=>select(selected+1));document.querySelectorAll('[data-language]').forEach(b=>b.addEventListener('click',()=>{language=b.dataset.language;try{localStorage.setItem('preferredLanguage',language)}catch{}render();}));render();
