-- Retro 1980 Supabase schema
-- Security baseline: public users can read site configuration, but only authenticated
-- users carrying app_metadata.role = 'admin' may modify it.
--
-- IMPORTANT: After creating the admin user in Supabase Auth, set the user's
-- app_metadata.role to "admin" from a trusted admin environment/dashboard.

-- -----------------------------------------------------------------------------
-- Menu items
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    action_id TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Prevent duplicate menu rows when this setup script is executed more than once.
CREATE UNIQUE INDEX IF NOT EXISTS menu_items_action_id_key
    ON public.menu_items (action_id);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

-- Remove legacy permissive policies.
DROP POLICY IF EXISTS "Enable read access for all users" ON public.menu_items;
DROP POLICY IF EXISTS "Enable all access for all users" ON public.menu_items;
DROP POLICY IF EXISTS "Public can read active menu items" ON public.menu_items;
DROP POLICY IF EXISTS "Admins can manage menu items" ON public.menu_items;

CREATE POLICY "Public can read active menu items"
ON public.menu_items
FOR SELECT
TO anon, authenticated
USING (is_active = TRUE OR (auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

CREATE POLICY "Admins can manage menu items"
ON public.menu_items
FOR ALL
TO authenticated
USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- -----------------------------------------------------------------------------
-- Site assets
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.site_assets (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.site_assets ENABLE ROW LEVEL SECURITY;

-- Remove legacy permissive policies.
DROP POLICY IF EXISTS "Enable read access for all users" ON public.site_assets;
DROP POLICY IF EXISTS "Enable all access for all users" ON public.site_assets;
DROP POLICY IF EXISTS "Public can read site assets" ON public.site_assets;
DROP POLICY IF EXISTS "Admins can manage site assets" ON public.site_assets;

CREATE POLICY "Public can read site assets"
ON public.site_assets
FOR SELECT
TO anon, authenticated
USING (TRUE);

CREATE POLICY "Admins can manage site assets"
ON public.site_assets
FOR ALL
TO authenticated
USING ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
WITH CHECK ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

-- -----------------------------------------------------------------------------
-- Storage bucket reminder
-- -----------------------------------------------------------------------------
-- The retro_assets bucket must NOT allow anonymous INSERT/UPDATE/DELETE.
-- In Supabase Storage policies, allow public SELECT only if public image access is
-- required, and require app_metadata.role = 'admin' for write operations.

-- -----------------------------------------------------------------------------
-- Default data
-- -----------------------------------------------------------------------------
INSERT INTO public.menu_items (label, action_id, order_index) VALUES
('🏃 골목길 (놀이)', 'playground', 1),
('🏫 교실 풍경', 'school', 2),
('🍭 학교 앞 문방구', 'store', 3),
('📰 그 시절 뉴스', 'timeline', 4),
('🖼️ AI 추억 복원', 'prompts', 5)
ON CONFLICT (action_id) DO NOTHING;

INSERT INTO public.site_assets (key, value, description) VALUES
('main_title', '응답하라 1980', 'The main H1 title'),
('main_subtitle', '국민학교와 중학교 시절의 따뜻한 추억 기록장', 'The subtitle'),
('img_marbles_main', 'images/retro_alley_marbles.png', '구슬치기 대백과 메인 이미지'),
('img_ddakkji', 'images/retro_ddakkji_game.png', '딱지치기 이미지'),
('img_rubber_band', 'images/retro_rubber_band_game.png', '고무줄 놀이 이미지'),
('img_hopscotch', 'images/retro_hopscotch.png', '사방치기 이미지'),
('img_lunchbox', 'images/retro_school_lunchbox.png', '양철 도시락 이미지'),
('img_nametag', 'images/retro_nametag_handkerchief.png', '명찰과 손수건 이미지'),
('img_stool', 'images/retro_stool_envelope.png', '채변 봉투 이미지'),
('img_chalkboard', 'images/retro_chalkboard_names.png', '떠든 사람 명단 이미지'),
('img_uniform', 'images/retro_school_uniform_reveal.png', '교련복 공개 이미지'),
('img_snacks_main', 'images/retro_stationery_store_snacks.png', '문방구 메인 이미지'),
('img_baseball', 'images/retro_baseball_1982.png', '프로야구 이미지'),
('img_gallery_winter', 'images/retro_classroom_winter.png', '갤러리: 겨울 교실'),
('img_gallery_store', 'images/stationery_store.png', '갤러리: 문방구'),
('img_gallery_olympic', 'images/olympic_88.png', '갤러리: 올림픽'),
('img_90s_arcade', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=600', '90s 오락실 이미지'),
('img_90s_fashion', 'images/90s_fashion.png', '90s 패션 이미지')
ON CONFLICT (key) DO NOTHING;
