-- Create Menu Items Table
CREATE TABLE IF NOT EXISTS menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label TEXT NOT NULL,
    action_id TEXT NOT NULL,
    order_index INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE menu_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON menu_items;
CREATE POLICY "Enable read access for all users" ON menu_items FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all access for all users" ON menu_items;
CREATE POLICY "Enable all access for all users" ON menu_items FOR ALL USING (true);

-- Create Site Assets Table
CREATE TABLE IF NOT EXISTS site_assets (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE site_assets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Enable read access for all users" ON site_assets;
CREATE POLICY "Enable read access for all users" ON site_assets FOR SELECT USING (true);
DROP POLICY IF EXISTS "Enable all access for all users" ON site_assets;
CREATE POLICY "Enable all access for all users" ON site_assets FOR ALL USING (true);

-- Storage Bucket Setup (Reminder: Check Dashboard)

-- Insert Default Data
INSERT INTO menu_items (label, action_id, order_index) VALUES
('🏃 골목길 (놀이)', 'playground', 1),
('🏫 교실 풍경', 'school', 2),
('🍭 학교 앞 문방구', 'store', 3),
('📰 그 시절 뉴스', 'timeline', 4),
('🖼️ AI 추억 복원', 'prompts', 5)
ON CONFLICT DO NOTHING;

-- Insert Image Assets (Mapping existing local paths)
INSERT INTO site_assets (key, value, description) VALUES
('main_title', '응답하라 1980', 'The main H1 title'),
('main_subtitle', '국민학교와 중학교 시절의 따뜻한 추억 기록장', 'The subtitle'),
('img_marbles_main', 'images/retro_alley_marbles.png', '구슬치기 대백과 메인 이미지'),
('img_ddakkji', 'images/retro_ddakkji_game.png', '딱지치기 이미지'),
('img_rubber_band', 'images/retro_rubber_band_game.png', '고무줄 놀이 이미지'),
('img_hopscotch', 'images/retro_hopscotch.png', '사방치기 이미지'),
('img_lunchbox', 'images/retro_school_lunchbox.png', '양철 도시락 이미지'),
('img_nametag', 'images/retro_nametag_handkerchief.png', '명찰과 손수건 이미지'),
('img_stool', 'images/retro_stool_envelope.png', '채변 봉투 이미지'),
('img_chalkboard', 'images/retro_chalkboard_names.png', '떠든 사람 명단 이미지'),
('img_uniform', 'images/retro_school_uniform_reveal.png', '교련복 공개 이미지'),
('img_snacks_main', 'images/retro_stationery_store_snacks.png', '문방구 메인 이미지'),
('img_baseball', 'images/retro_baseball_1982.png', '프로야구 이미지'),
('img_gallery_winter', 'images/retro_classroom_winter.png', '갤러리: 겨울 교실'),
('img_gallery_store', 'images/stationery_store.png', '갤러리: 문방구'),
('img_gallery_olympic', 'images/olympic_88.png', '갤러리: 올림픽'),
('img_90s_arcade', 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&q=80&w=600', '90s 오락실 이미지'),
('img_90s_fashion', 'images/90s_fashion.png', '90s 패션 이미지')
ON CONFLICT DO NOTHING;
